-- MySQL Script generated by MySQL Workbench
-- Sun Mar 31 16:25:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Script to input into existing MySQL 8 database.

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema github_search
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `github_search` ;

-- -----------------------------------------------------
-- Schema github_search
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `github_search` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `github_search` ;

-- -----------------------------------------------------
-- Table `github_search`.`repo_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `github_search`.`repo_info` ;

CREATE TABLE IF NOT EXISTS `github_search`.`repo_info` (
  `repo_id` INT(11) NOT NULL,
  `repo_owner_id` INT(11) NULL DEFAULT NULL,
  `repo_user` VARCHAR(256) NULL DEFAULT NULL,
  `repo_name` VARCHAR(256) NULL DEFAULT NULL,
  `repo_full_name` VARCHAR(256) NULL DEFAULT NULL,
  `repo_updated_ts` DATETIME NULL DEFAULT NULL,
  `repo_size` INT(11) NULL DEFAULT NULL,
  `repo_cloned` ENUM('cloned', 'not_cloned') NULL DEFAULT NULL,
  `repo_description` VARCHAR(4096) NULL DEFAULT NULL,
  `repo_last_checked` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `repo_latest_commit` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`repo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `github_search`.`repo_search_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `github_search`.`repo_search_results` ;

CREATE TABLE IF NOT EXISTS `github_search`.`repo_search_results` (
  `match_master_id` INT(11) NOT NULL AUTO_INCREMENT,
  `match_repo_id` INT(11) NULL DEFAULT NULL,
  `match_inserted` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `match_type` VARCHAR(256) NULL DEFAULT NULL,
  `match_string` VARCHAR(256) NULL DEFAULT NULL,
  `match_location` VARCHAR(1024) NULL DEFAULT NULL,
  `match_line` VARCHAR(8192) NULL DEFAULT NULL,
  `match_item_entropy` DECIMAL(17,15) NULL DEFAULT NULL,
  `match_line_hash` VARCHAR(64) NULL DEFAULT NULL,
  `match_update_type` VARCHAR(10) NULL DEFAULT NULL,
  `match_commit_hash` VARCHAR(45) NULL DEFAULT NULL,
  `match_commit_author` VARCHAR(256) NULL DEFAULT NULL,
  `match_commit_time` VARCHAR(64) NULL DEFAULT NULL,
  `match_commit_message` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`match_master_id`),
  UNIQUE INDEX `match_master_id_UNIQUE` (`match_master_id` ASC) VISIBLE,
  UNIQUE INDEX `match_line_hash_UNIQUE` (`match_line_hash` ASC) VISIBLE,
  INDEX `repo_id` (`match_repo_id` ASC) VISIBLE,
  CONSTRAINT `repo_id`
    FOREIGN KEY (`match_repo_id`)
    REFERENCES `github_search`.`repo_info` (`repo_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 54888
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
